### PR TITLE
Add `Login with LinkedIn` demo

### PR DESCRIPTION
**Pull request by kamal250**

### CODE REVIEW

**Comment by zachleat** [comment]
I’m having trouble testing this, it looks like I need a LinkedIn company page to create an OAuth app?

image

**Comment by kamal250** [comment]
Yes, it is weird but required to create a LinkedIn company page (I have created "11ty serverless oauth demo" within my linkedin developer account) and then we should add "Sign In with LinkedIn" product.

image
image

**Comment by zachleat** [comment]
Ah, thank you! I was able to make it further. Now I’m stuck again:

image

How do I add the scope to my app on LinkedIn? I don’t see any way to do it and I’m getting unauthorized scope errors.

**Comment by kamal250** [comment]
image

I hope you have verified the app, once you click on "verify" button, admin associated with company will have a request that must be approved.

**Comment by kamal250** [comment]
Do you need any help further?

**Comment by zachleat** [comment]
The DX of the LinkedIn dev site is missing a few things but I am able to make progress again after finding this StackOverflow post: https://stackoverflow.com/questions/53479131/unauthorized-scope-error-in-linkedin-oauth2-authentication

**Comment by zachleat** [comment]
Merged, thank you!

**Pull request merged**
